version: 2
updates:

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker-compose"
    directory: "/config"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/config"
    schedule:
      interval: "daily"
