version: 2
updates:

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/config"
    schedule:
      interval: "weekly"
