name: Pull Request to Master

on:
  pull_request:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        id: init
        run: ./scripts/terraform.sh init -no-color
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          HCLOUD_DNS_TOKEN: ${{ secrets.HCLOUD_DNS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      - name: Terraform plan
        id: plan
        run: ./scripts/terraform.sh plan -no-color
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          HCLOUD_DNS_TOKEN: ${{ secrets.HCLOUD_DNS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
      - name: Add comment
        uses: thollander/actions-comment-pull-request@v2
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          comment_tag: execution
          message: |
            #### Terraform Initialization: `${{ steps.init.outcome }}`
            #### Terraform Plan: `${{ steps.plan.outcome }}`
            
            <details>
            <summary>Show Plan</summary>
            
            ```
            ${{ env.PLAN }}
            ```
            
            </details>
