name: Push to Master

on:
  push:
    branches:
      - master
  workflow_dispatch: # allow manual triggering

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v1
      - name: Terraform init
        run: |
          chmod +x ./scripts/hello.sh
          ./scripts/hello.sh